# auth.py
import bcrypt
from database import get_conn

def hash_password(pw): ...
def verify_password(pw, stored): ...
def login_user(user, pw): ...
def signup_user(user, pw): ...
def renew_subscription(user, plan): ...
# add login attempt rate limiter here
